name: Test
on: push
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Testing
      env:
        SECRET: ${{secrets.Test}}
      - run: |
          echo "Secret is SECRET"
          
          
